[package]
name = "tx"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
abstract-tx = { path = "../abstract-tx" }
